#!/usr/bin/python
# -*- coding: UTF-8 -*-

"""
This is a phonelog GTK+ GUI, designed to use with a custom daemon,
the SHR daemon, and when ready, opimd.

Written by Tom Hacohen. (tom@stosb.com)

Licensed by GPLv2
"""

__version__ = "0.15.3"

import dbus
import gobject, gtk
from datetime import datetime
import time
import os.path
import sqlite3
import shutil
import re

try:
	import mokoui
	use_mokoui = True
except:
	use_mokoui = False

#constants
"""PHONELOG_BUSNAME = "org.freesmartphone.opimd"
PHONELOG_OBJECTPATH = "/org/freesmartphone/PIM/Log"
PHONELOG_INTERFACE = "org.freesmartphone.PIM.Log.Calls"
"""

PHONELOG_BUSNAME = "org.smartphone.opimd"
PHONELOG_OBJECTPATH = "/org/smartphone/PIM/Log"
PHONELOG_INTERFACE = "org.smartphone.PIM.Log.Calls"

CONTACTS_BUSNAME = 'org.freesmartphone.ogsmd'
CONTACTS_OBJECTPATH = '/org/freesmartphone/GSM/Device'
CONTACTS_INTERFACE = 'org.freesmartphone.GSM.SIM'

PHONE_BUSNAME = 'org.freesmartphone.ogsmd'
PHONE_OBJECTPATH = '/org/freesmartphone/GSM/Device'
PHONE_INTERFACE = 'org.freesmartphone.GSM.Call'

CONFIGURATION_DIR = "/home/root/.phonelog/"
TIME_FILE = CONFIGURATION_DIR + "time.dat"
CONFIGURATION_FILE = CONFIGURATION_DIR + "phonelog.conf"
DEMO_CONFIG_PATH = "/usr/share/phonelog/skeleton/phonelog.conf"
ICONS_PATH = "/usr/share/phonelog/icons/"

#OPHONEKITD related
OPHONEKITD_DB = "/var/db/phonelog.db"
CALL_STATUS_INCOMING = 0
CALL_STATUS_OUTGOING = 1
CALL_STATUS_ACTIVE = 2
CALL_STATUS_HELD = 3
CALL_STATUS_RELEASE = 4

#PAGES POSITIONS
PAGE_INCOMING = 0 
PAGE_OUTGOING = 1
PAGE_MISSED = 2
PAGE_GENERAL = 3
PAGE_SETTINGS = 4

class Configuration:
	__configuration = None
	__filename = None
	def __init__(self, file):
		"""
		Reads the signal list from the file given as parameter
		(to launch, interface, busname, path, signal, rules) from to_launch=interface;busname;path;signal;rule1,rule2...
		"""
		self.initConfiguration()
		self.setFilename(file)
		self.setDefault()
		
		if not os.path.exists(file):
			shutil.copy(DEMO_CONFIG_PATH, file)

		print "Using configuration:"
		print "*********************"
		self.extractFromFile()		
		print "*********************"
		print "End of configuration"
			
	def initConfiguration(self):
		self.__configuration = dict()
	def extractFromFile(self):
		file = self.getFilename()
		regex = re.compile('^\s*([^=\s]*)\s*=\s*(.*)\s*\n$')
		comment_regex = re.compile('^\s*#')
		FILE = open(file,'r')

		
		for line in FILE:
			if not comment_regex.match(line):
				parsed = regex.match(line)
				#ignore bad config lines
				if parsed != None:
					print line
					self.set(parsed.group(1), parsed.group(2))
		FILE.close()
		
	def setDirect(self, name, value):
		self.__configuration[name] = value
	def set(self, name, string):
		boolean_value = self.__extractBoolean(string)
		if boolean_value != None:
			self.setDirect(name, boolean_value)
			return

		numeric_value = self.__extractNumeric(string)
		if numeric_value != None:
			self.setDirect(name, numeric_value)
			return
		else:
			self.setDirect(name, string)
			return
	def get(self, name):
		if name in self.__configuration:
			return self.__configuration[name]
		else:
			return None
	def setDefault(self):
		self.setDirect('phonekitd', True)
		self.setDirect('received_limit', 50)
		self.setDirect('made_limit', 50)
		self.setDirect('missed_limit', 50)
		self.setDirect('general_limit', 50)

		self.setDirect('received_tab_name', "Received")
		self.setDirect('made_tab_name', "Made")
		self.setDirect('missed_tab_name', "Missed")
		self.setDirect('general_tab_name', "General")
		self.setDirect('received_tab_type', 'icon')
		self.setDirect('made_tab_type', 'icon')
		self.setDirect('missed_tab_type', 'icon')
		self.setDirect('general_tab_type', 'icon')
		self.setDirect('received_tab_image_file', "received.png")
		self.setDirect('made_tab_image_file', "made.png")
		self.setDirect('missed_tab_image_file', "missed.png")
		self.setDirect('general_tab_image_file', "general.png")
		
		self.setDirect('startup_tab', "missed")
		self.setDirect('time_format', "%d-%m-%Y %H:%M:%S")
		self.setDirect('received_mark', "↓")
		self.setDirect('made_mark', "↑")
		self.setDirect('missed_mark', "↺")
		return
	def __extractBoolean(self, string):
		low_case = string.lower()
		if low_case == "false":
			return False
		elif low_case == "true":
			return True
		else:
			return None
	def __extractNumeric(self, string):
		if re.match('^\d+$',string):
			return int(string)
		elif re.match('^\d+.?\d*$',string):
			return float(string)
		else:
			return None


	def setFilename(self, file):
		self.__filename = file
	def getFilename(self):
		return self.__filename
	def getDictionary(self):
		return self.__configuration
	def writeToFile(self):
		file = self.getFilename()
		FILE = open(file,'w')
		FILE.truncate(0)
		
		for option in self.getDictionary():
			FILE.write(option + ' = ' + str(self.get(option)) + "\n")
			
		FILE.close()

class LastTime(Configuration):
	def __init__(self, file):
		self.setFilename(file)
		self.initConfiguration()
		self.setDefault()
		if os.path.exists(file):
			print "Last viewed times:"
			print "*********************"
			self.extractFromFile()		
			print "*********************"
			print "End of times"		
		else:
			self.writeToFile()	
	def setDefault(self):
		self.set('incoming', 1)
		self.set('outgoing', 1)
		self.set('missed', 1)
		self.set('all', 1)
	def get(self, type):
		last_time = Configuration.get(self, type)
		if last_time == None:
			self.set(type)
			last_time = self.get(type)
		return last_time
	def set(self, type, last_time = None):
		if last_time == None:
			last_time = time.time()
		else:
			last_time = float( last_time )
		self.setDirect(type, last_time )

class CallsTab:
	#POSITION IN MODEL
	CONTACT_POSITION = 0
	NUMBER_POSITION = 1
	DATE_POSITION = 2
	DURATION_POSITION = 3
	VISUAL_POSITION = 4
	STATUS_POSITION = 5
	
	#ACTUAL GUI POSTITON
	CONTACT_COLUMN = 0
	DATE_COLUMN = 1
	__list = None
	__contact_show_column = CONTACT_POSITION
	__date_show_column = DATE_POSITION
	__tab = None
	__type = None
	__mark_new = False
	
	def __init__(self, type, mark_new = False):
		self.createList()
		self.__type = type
		self.__createCallsTab()
		self.last_refresh = RefreshTime.get(self.__type)
		self.__mark_new = mark_new
	def getList(self):
		return self.__list

	def getTab(self):
		return self.__tab
	def shouldMarkNew(self):
		return self.__mark_new
	def __getContactColumn(self):
		return self.CONTACT_COLUMN
	def __getDateColumn(self):
		return self.DATE_COLUMN

	def __createCallsTab(self):
		page = gtk.VBox()
		page.pack_start( self.__initScrolled() )
		buttons = gtk.HBox()
		page.pack_start(buttons, False, padding = 1)

		callButton = gtk.Button("Call")
		callButton.connect ("clicked", self.callButton_clicked)

		numberButton = gtk.Button("Show Numbers")
		numberButton.connect ("clicked", self.numberButton_clicked)

		durationButton = gtk.Button("Show Duration")
		durationButton.connect ("clicked", self.durationButton_clicked)

		buttons.pack_start(callButton, True, padding = 1)
		buttons.pack_start(numberButton, True, padding = 1)
		buttons.pack_start(durationButton, True, padding = 1)
		
		self.__tab = page
	def __createTreeView(self):
		self.__list = gtk.TreeView (gtk.TreeStore( gobject.TYPE_STRING, 
					gobject.TYPE_STRING,
					gobject.TYPE_STRING,
					gobject.TYPE_STRING,
					gobject.TYPE_BOOLEAN,  #the boolean is there for coloring
					gobject.TYPE_STRING ) #should be changed to an icon?
					)
	def createList(self):

		self.__createTreeView()
			
		renderer = gtk.CellRendererText()
		#change text size as well?
		renderer.set_property('weight', 800)

		column0 = gtk.TreeViewColumn("Contact", renderer, text=self.CONTACT_POSITION, weight_set=self.VISUAL_POSITION)
		self.__list.insert_column( column0, self.__getContactColumn() )
		column0 = gtk.TreeViewColumn("Time", renderer, text=self.DATE_POSITION, weight_set=self.VISUAL_POSITION)
		self.__list.insert_column( column0, self.__getDateColumn())
		
	def __initScrolled(self):
		tab_content = self.__list
		if use_mokoui:
			scrolled = mokoui.FingerScroll()
		else:
			scrolled = gtk.ScrolledWindow()
			scrolled.set_policy(gtk.POLICY_NEVER, gtk.POLICY_AUTOMATIC)

		scrolled.add_with_viewport(tab_content)
		return scrolled
		
	def __getCalls(self):
		type = self.__type
		if config.get('phonekitd'):
			calls = getPhonekitCallsList(type)
			if len(calls) == 0:
				return None				
		else:
			global phoneLog
			legacy_limit = typeFromLegacyDaemonType(type)
			calls = phoneLog.GetCallsList(type, config.get(legacy_limit + "_limit"))
			try: #hack because i send dbus empty
				calls[0]
			except:
				return None
		return calls
	def populateList(self, group_type = 1):
		"""
		group_type =
		0 - never group
		1/everything else - always group
		2 - group from the same type only.
		"""
		list = self.__list
		type = self.__type
		previous_time = datetime.fromtimestamp(RefreshTime.get(type))
		visual_flag = self.shouldMarkNew()

		calls = self.__getCalls()
		if calls == None:
			return False
			
		#get and clear the model.
		model = list.get_model()
		model.clear()

		
		last_parent_added = None
		
		for call in calls:
			
			number = call[0]
			contact = getContact(number)
			timestamp = float(call[1])	
			call_time = datetime.fromtimestamp( timestamp )
			status = call[2]

			if config.get('phonekitd'):
				active_time = call[3]

				#untill the change will be coded in the daemon
				if active_time == None:
					active_time = "00:00"
			else:
				active_time = "No legacy support"

			#hack because of the (frameworks?) double quotes bug
			number = number.strip('"')
			
			#handle grouping types
			sametype_group = False
			if group_type == 0:
				#if we don't want to group, parent is always None
				last_parent_added = None
			elif group_type == 2:
				sametype_group = True
				#HACK FOR THE GENERAL LIST
				if config.get('phonekitd'):
					if active_time == "00:00":
						status += 2

			missed = (status == 2)
				
			#check if should be grouped
			parent = None
			if last_parent_added != None:
				if (((last_contact == contact) and (contact != "")) \
						or (last_number == number))\
					and (not sametype_group or last_status == status):
							
					parent = last_parent_added
				

			#update the last_statuses so we won't rely on the GUI
			last_contact = contact
			last_number = number
			last_status = status
			last_missed = missed

			#We want the contact to show as the number if it's not in the phonebook.
			if contact == "":
				contact = number
			
			#style status
			if status == 0:
				status = config.get('received_mark')
			elif status == 1:
				status = config.get('made_mark')
			elif status == 2:
				status = config.get('missed_mark')
				
			
			parent_added = model.append(parent, ( contact , 
					number ,
					call_time.strftime(config.get('time_format') ) ,
					active_time, 
					visual_flag and (call_time > previous_time) ,
					status
					)
				)

			if parent == None:
				last_parent_added = parent_added

		#Set last refresh time
		RefreshTime.set(type)
		return True										


	def callButton_clicked (self, button):
		global phoneObject
		list = self.__list
		
		number = self.__getSelectedNumber()
		
		if number != None:
			#TODO, once the highlevel api work, change to them.
			phoneObject.Initiate (number, 'voice')
		
	def numberButton_clicked (self, button):
		list = self.__list

		get_column = self.__getContactColumn()

		contact_column = list.get_column(get_column)
		renderer = contact_column.get_cell_renderers()[0]

		
		if self.__contact_show_column == self.CONTACT_POSITION:
			self.__contact_show_column = self.NUMBER_POSITION
			button_label = "Show Names"

		else:
			self.__contact_show_column = self.CONTACT_POSITION
			button_label = "Show Numbers"
			
		button.set_label(button_label)
		contact_column.set_attributes(renderer, text=self.__contact_show_column)

		
		
	def durationButton_clicked (self, button):
		list = self.__list
		
		get_column = self.__getDateColumn()

		date_column = list.get_column(get_column)
		renderer = date_column.get_cell_renderers()[0]

		
		if self.__date_show_column == self.DATE_POSITION:
			self.__date_show_column = self.DURATION_POSITION
			button_label = "Show Date"

		else:
			self.__date_show_column = self.DATE_POSITION
			button_label = "Show Duration"
			
		button.set_label(button_label)
		date_column.set_attributes(renderer, text=self.__date_show_column)

		
		
	
	def __getSelectedNumber(self):
		list = self.__list
		selected = list.get_selection().get_selected_rows()
		selected = selected[1][0]

		row = list.get_model()[selected]

		number = row[self.NUMBER_POSITION]
		return number
	def addToTab(self, notebook):
		type = typeFromLegacyDaemonType(self.__type)
		if config.get(type + '_tab_type') == 'icon':
			tabWidget = gtk.Image()
			image_path = config.get(type + '_tab_image_file')

			#if not absolute
			if image_path[0] != '/':
				image_path = ICONS_PATH + image_path
				
			tabWidget.set_from_file(image_path)
		else:
			tabWidget = gtk.Label(config.get(type + '_tab_name') )
		
		notebook.insert_page(self.getTab(), tabWidget)
class GeneralTab (CallsTab):
	#ACTUAL GUI POSTITON
	STATUS_COLUMN = 0	
	CONTACT_COLUMN = 1
	DATE_COLUMN = 2
	def __getStatusColumn(self):
		return self.STATUS_COLUMN
		
	def createList(self):
		CallsTab.createList(self)
		
		renderer = gtk.CellRendererText()
		renderer.set_property('weight', 800)
		renderer.set_property('size-points', 8)
		
		column0 = gtk.TreeViewColumn("Status", renderer, text=self.STATUS_POSITION)
		list = self.getList()
		list.insert_column( column0, self.__getStatusColumn() )
	def populateList(self, group_type = None):
		if group_type == None:
			group_type = 2
		CallsTab.populateList(self, 2)
	


#GENERAL PURPOSE FUNCTIONS
def useOphonekit():
	return os.path.exists(OPHONEKITD_DB)
	
	
def stringToTabNumber(string):
	if string.lower() == "received":
		return PAGE_INCOMING
	elif string.lower() == "made":
		return PAGE_OUTGOING
	elif string.lower() == "missed":
		return PAGE_MISSED
	elif string.lower() == "general":
		return PAGE_GENERAL
def typeFromLegacyDaemonType(type):
	if type == "incoming":
		return 'received'
	elif type == "outgoing":
		return 'made'
	elif type == "missed":
		return 'missed'
	elif type == "all":
		return 'general'
	else:
		return "received"
#END OF GENERAL PURPOSE FUNCTIONS


#GET/EDIT DATA FUNCTIONS
def getContact(number):
	global contacts
	for contact in contacts:
		if comparePhoneNumber(contact[2], number):
			return contact[1]
	return ""

def comparePhoneNumber(number1, number2):
	'''
	Compares two phone numbers. They are considered equal if:
	a) One does not contain digits, and they are equal as strings
	or
	b) Both start with a "+", and all following digits are equal
	or
	c) At least one of them does not start with a "+", and the
	   last 7 digits are equal
	'''
	digits1 = filter (lambda c: c.isdigit() or c == '+', number1)
	digits2 = filter (lambda c: c.isdigit() or c == '+', number2)

	if digits1 == '' or digits2 == '':
		return number1 == number2
	if digits1[0] == digits2[0] == '+':
		return digits1 == digits2
	else:
		return digits1[-7:] == digits2[-7:]
		
def getPhonekitCallsList(type):
	get_fields = "number, strftime('%s',startTime), direction, duration"
	#if type == "missed":
	#	calls = database.execute("SELECT %s FROM missed_calls WHERE direction = ? ORDER BY startTime DESC LIMIT ?" % (get_fields,  ) ,\
	#		(CALL_STATUS_INCOMING, config.get('missed_limit'))).fetchall()
	if type == "missed":
		calls = database.execute("SELECT %s FROM calls WHERE direction = ? AND activeTime IS NULL ORDER BY startTime DESC LIMIT ?" % (get_fields, ), \
		(CALL_STATUS_INCOMING, config.get('missed_limit'))).fetchall()
	elif type == "incoming":
		calls = database.execute("SELECT %s FROM calls WHERE direction = ? AND activeTime IS NOT NULL ORDER BY startTime DESC LIMIT ?" % (get_fields, ), \
		(CALL_STATUS_INCOMING, config.get('received_limit'))).fetchall()
	elif type == "outgoing":
		calls = database.execute("SELECT %s FROM calls WHERE direction = ? ORDER BY startTime DESC LIMIT ?" % (get_fields, ), \
			(CALL_STATUS_OUTGOING, config.get('made_limit'))).fetchall()
	elif type == "all":
		calls = database.execute("SELECT %s FROM calls ORDER BY startTime DESC LIMIT ?" % (get_fields, ), \
			(config.get('general_limit'),) ).fetchall()
	else:
		return None
	return calls
	

#END OF GET/EDIT DATA

#DBUS FUNCTIONS
def getDbusObject (bus, busname , objectpath , interface):
	dbusObject = bus.get_object(busname, objectpath)
	return dbus.Interface(dbusObject, dbus_interface=interface)
def getPhoneLogObject (bus, busname = PHONELOG_BUSNAME, objectpath = PHONELOG_OBJECTPATH, interface = PHONELOG_INTERFACE):
	return getDbusObject (bus, busname , objectpath , interface)

def getContactsObject (bus, busname = CONTACTS_BUSNAME, objectpath = CONTACTS_OBJECTPATH, interface = CONTACTS_INTERFACE):
	return getDbusObject (bus, busname , objectpath , interface)

def getPhoneObject (bus, busname = PHONE_BUSNAME, objectpath = PHONE_OBJECTPATH, interface = PHONE_INTERFACE):
	return getDbusObject (bus, busname , objectpath , interface)
	
#END OF DBUS FUNCTIONS


#GTK
#Callbacks
def cb_notebook_switch_page (notebook, page, page_num):
	if page_num == PAGE_INCOMING:
		incoming.populateList()
	elif page_num == PAGE_OUTGOING:
		outgoing.populateList()
	elif page_num == PAGE_MISSED:
		missed.populateList()
	elif page_num == PAGE_GENERAL:
		general.populateList()
#End of GTK

#create the config dir if doesn't exist.
if not os.path.exists(CONFIGURATION_DIR):
	os.mkdir(CONFIGURATION_DIR)

systemBus = dbus.SystemBus()
config = Configuration(CONFIGURATION_FILE)

#init db

if config.get('phonekitd'):
	if not os.path.exists(OPHONEKITD_DB):
		print "Can't Find " + OPHONEKITD_DB + " Falling back to the daemon"
		phoneLog = getPhoneLogObject(systemBus)
		config.setDirect('phonekitd', False)
	database = sqlite3.connect(OPHONEKITD_DB)	
else:
	phoneLog = getPhoneLogObject(systemBus)
	

#init dbus
contactsObject = getContactsObject(systemBus)
phoneObject = getPhoneObject(systemBus)

#init gtk
win = gtk.Window()
win.connect('delete-event', gtk.main_quit)
win.set_title("Phone Log")

RefreshTime = LastTime(TIME_FILE)

incoming = CallsTab('incoming')
outgoing = CallsTab('outgoing')
missed = CallsTab('missed', True)
general = GeneralTab('all')

notebook= gtk.Notebook()

win.add (notebook)

incoming.addToTab(notebook)
outgoing.addToTab(notebook)
missed.addToTab(notebook)
general.addToTab(notebook)

win.show_all()

startup_page = stringToTabNumber( config.get('startup_tab') )
notebook.set_current_page(startup_page)

notebook.connect('switch-page', cb_notebook_switch_page)
#retrieve contacts
contacts = contactsObject.RetrievePhonebook("contacts")

incoming.populateList()
outgoing.populateList()
missed.populateList()
general.populateList()

#start


gtk.main()

RefreshTime.writeToFile()

if config.get('phonekitd'):
	database.close()
